### ISSUE TITLE
find_pkg_data_path deprecated in Astropy 5.0

### ISSUE THREAD

**Issue by PatrickOgle** [desihub/speclite#74]
sdss = speclite.filters.load_filters('sdss2010-*')

gives the following error in Astropy 5.0:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-c73b57f81d52> in <module>
----> 1 sdss = speclite.filters.load_filters('sdss2010-*')
      2 speclite.filters.plot_filters(sdss, wavelength_limits=(3000, 11000))

~/miniconda3/envs/science/lib/python3.8/site-packages/speclite/filters.py in load_filters(*names)
   1805     """
   1806     # Replace any group wildcards with the corresponding canonical names.
-> 1807 
   1808 
   1809     filters_path = get_path_of_data_file('filters/')

AttributeError: module 'astropy.utils.data' has no attribute '_find_pkg_data_path'

-----------------------------------------------------------------------------

According to the Astropy 5.0 changelog: https://docs.astropy.org/en/stable/changelog.html

astropy.utils.data.get_pkg_data_path is publicly scoped (previously the private function _find_pkg_data_path) for obtaining file paths without checking if the file/directory exists, as long as the package and module do. [#11006]

**Comment by sbailey** [comment]
It looks like this is already fixed in main (`get_path_of_data_file` uses Python standard library `pkg_resources.resource_filename` instead of astropy custom data finder), and I don't see any references to "get_pkg_data" or "find_pkg_data" in the code (admittedly, I don't have astropy 5.0 installed and haven't tried setting up a custom environment to test it).

i.e. do we just need a new speclite tag?

**Comment by PatrickOgle** [comment]
Actually, I just got it to work in Astropy 5.0 after reinstalling the latest speclite.  Maybe something was stale in my installation. Sorry for the false alarm.
